<!DOCTYPE html>
<html lang="en">

<head>
    <title>Not found</title>
    <meta charset="UTF-8">

    <!-- copy paste mo rin to sa lahat @lim -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--  -->

    <link rel="stylesheet" href="/xampp/library-system-latest/src/style/notfound.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Document</title>
</head>

<body>
    <div>
        <h1>Not Found</h1>
        <i class="fa-solid fa-triangle-exclamation fa-beat"></i>
        <p>
            <?= "cannot find " . $_SERVER['REQUEST_URI']; ?>
        </p>

        <?php
        $page = rtrim($_SERVER['REQUEST_URI'], "/");
        $req_uri = parse_url($_SERVER['REQUEST_URI']);
        $path = $req_uri['path'];

        $path_exp = explode("/", $path);
        $req_index = array_search("library-system-latest", $path_exp) + 1;

        

        $req_path = rtrim("/" . implode("/", array_slice($path_exp, $req_index)), "/");

        if (Router::find("GET" . $req_path)) header("location:".rtrim(implode("/", array_slice($path_exp,0,$req_index)), "/"));
        ?>

        <br>
        <a class="link_btn" href=<?= rtrim(implode("/", array_slice($path_exp,0,$req_index)), "/") ?>>go to home</a>
    </div>
</body>

</html>