<!DOCTYPE html>

<html lang="en">



<head>
    <title>Not found</title>
    <meta charset="UTF-8">

    <!-- copy paste mo rin to sa lahat @lim -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--  -->

    <link rel="stylesheet" href="/xampp/library-system-latest/src/style/notfound.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Document</title>
</head>

<body>
    <div>
        <h1>Not Found</h1>
        <i class="fa-solid fa-triangle-exclamation fa-beat"></i>
        <p>
            <?php echo "cannot find ".$_SERVER['REQUEST_URI'];?>
        </p>
    
        <a href="../home">go to home</a>
    </div>
</body>

</html>