<section id="book_preview" class="regis_form_con">

    <form>
        <section class="card_con ">
            <div class="card preview">
                <img id="book_prev_img" src="">
            </div>
            <div id="book_main_details">
                <p id="book_prev_title"> sample title </p>
                <p id="book_prev_author">(author)</p>
                <p id="book_prev_date">2020-11-29</p><br>
                <p id="book_prev_summary">summary</p>
            </div>

        </section>
        <div id="book_prev_button">
            <?php 
                if ($_SESSION['acc_type'] == 'user') {
                    if(  strpos( $_SERVER['REQUEST_URI'],"user/shelf") === false ) echo "<button> burrow </button>";
                    else echo " <p> code : </p>";
                } 
            ?>
        </div>
        <hr>
    
        <?php if( strpos( $_SERVER['REQUEST_URI'],"user/shelf") === false ) $bview->related_searches() ?>

    </form>
</section>

<section id="change_pass" class="regis_form_con">
    <form>
        <span><?= $view->Username($_SESSION['id']) ?></span><br>
        <input type="text" placeholder="Old password" name="old_pass" required><br>
        <input type="password" placeholder="New password" name="new_pass" required><br>
        <input type="password" placeholder="Confirm password" name="pass" required><br>
        <button type="submit">Update</button>
    </form>
</section>