<section id="return" class="regis_form_con">
    <form>
        <h1>Return</h1>
        <hr>
        <input type="text" name="return_code" placeholder="Return code">
            <button type="submit">
                Submit
            </button>
    </form>
</section>

<section id="borrow" class="regis_form_con">
    <form>
        <h1>Borrow</h1>
            <hr>
            <input type="text" name="borrow_code" placeholder="Borrow code">

            <button type="submit">
                Submit
            </button>
        </form>
</section>
