<nav id="side_nav">
    <div><span>Staff</span></div>
    <div id="add_staff"><span>Staff</span><i class="fa-solid fa-circle-plus"></i></div>
    <div id="add_user"><span>User</span><i class="fa-solid fa-circle-plus"></i></div>
    <div id="add_book"><span>Book</span><i class="fa-solid fa-circle-plus"></i></div>
    <div id="borrow_book"><span>Borrow</span><i class="fa-solid fa-circle-plus"></i></div>
    <div id="return_book"><span>Return</span><i class="fa-solid fa-circle-plus"></i></div>
</nav>