<section id="staff_regis" class="regis_form_con">
        <form data-type="createStaff">
            <h1>Staff Registration</h1>
            <hr>
            <input type="text" name="fn" placeholder="First Name" required>
            <input type="text" name="username" placeholder="Username" required><br>
            <input type="text" name="ln" placeholder="Last Name" required>
            <input type="password" name="password" placeholder="Password" required><br>
            <Button type="submit">Create</Button>
        </form>
</section>