<nav id="top_nav">

    <div id="search_con">
        <input id="book_search" type="text" placeholder="search" name="book_search">
        <div id="search_res">
        </div>
    </div>

    <img class="nav_button" src="../src/assets/logo.png">
    <p class="nav_button"><i class="fa-regular fa-calendar"></i></p>
    <p class="nav_button"><i class="fa-regular fa-envelope"></i></p>
    <p class="nav_button menu">
        <i class="fa-solid fa-ellipsis-vertical menu"></i>
    </p>
    <div id="menu_opt_con">
        <p id="about_us">about us</p>
        <p id="logout">logout</p>
        <p id="update_pass">update password</p>
    </div>
</nav>