<section id="user_regis" class="regis_form_con">
        <form data-type="createUser">
            <h1>User Registration</h1>
            <hr>
            <input type="text" name="Studno" placeholder="Student Number(22-0556)" pattern="([0-9]{2})-([0-9]{4,8})" autocomplete="off" required>
            <input type="text" name="fn" placeholder="First Name" pattern="[a-z]*" required><br>
            <input type="text" name="ln" placeholder="Last Name" pattern="[a-z]*" required>
            <input type="text" name="grade/section" placeholder="Grade/Section" pattern="([a-z]*)/([0-9a-z]*)" required><br>
            <input type="email" name="email" placeholder="Email" required>
            <input type="text" name="contact_no" placeholder="Contact Number(09345678901)" pattern="09([0-9]{9,10})" required><br>
            <Button type="submit">Create</Button>
        </form>
</section>

    <section id="book_regis" class="regis_form_con">
        <form data-type="addBook">
            <h1>Add Books</h1>
            <hr>
            <input type="text" name="title" placeholder="Title" required>
            <input type="text" name="author" placeholder="Author"><br>
            <input type="date" name="date_release" placeholder="Date release(yyyy-mm-dd)">
            <input type="text" name="genre" placeholder="Genre"><br>
            <label for="cover_img">cover image</label>
            <input type="file" name="cover_img" accept="image/*"><br>
            <input type="text" name="publisher" placeholder="Publisher">
            <input type="text" name="language" placeholder="Language"><br>
            <Button type="submit">Create</Button>
        </form>
    </section>