<?php
    $view = new AdminView;
$bview = new BookView;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../src/style/style.css" rel="stylesheet" type=" text/css">

    <meta charset="UTF-8">

    <title>Admin home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="../src/js/forms.js" defer></script>
    <script src="../src/js/logout.js" defer></script>
    <script src="../src/js/search.js" defer></script>
    <script src="../src/js/nav_btns.js" defer></script>

</head>

<body>
    <?php
    get_temp("top_nav");
    ?>

    <h1>About us</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error minima, alias, laudantium est repellat doloremque nemo vel commodi deserunt aliquid quaerat ad sit vitae maxime consectetur possimus neque.</p>


    <!-- hidden sections -->

    <?php
    get_temp('loading_pop');
    get_temp("book_preview_change_pass_forms",["view"=>$view,"bview"=>$bview]);
    ?>
</body>

</html>