<?php

$view = new AdminView;
$bview = new BookView;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../src/style/style.css" rel="stylesheet" type=" text/css">

    <meta charset="UTF-8">

    <title>Admin home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="../src/js/forms.js" defer></script>
    <script src="../src/js/regis_forms.js" defer></script>
    <script src="../src/js/logout.js" defer></script>
    <script src="../src/js/book_prev.js" defer></script>
    <script src="../src/js/search.js" defer></script>
    <script src="../src/js/nav_btns.js" defer></script>

</head>

<body>
    <?php 
    require view("top_nav");
    require view("side_nav"); 
    $bview->new_books();
    $bview->new_release_books()
    ?>

    <!-- hidden sections -->

    <?php
    require view('loading_pop');
    require view("about_us");
    require view("transaction_form");
    require view("book_preview_change_pass_forms");
    require view("user_book_forms");
    ?>

    <section id="staff_regis" class="regis_form_con">
        <form data-type="createStaff">
            <h1>Staff Registration</h1>
            <hr>
            <input type="text" name="fn" placeholder="First Name" required>
            <input type="text" name="username" placeholder="Username" required><br>
            <input type="text" name="ln" placeholder="Last Name" required>
            <input type="text" name="password" placeholder="Password" required><br>
            <Button type="submit">Create</Button>
        </form>
    </section>

</body>

</html>