<?php
    $view = new StaffView;
    $bview = new BookView;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../src/style/style.css" rel="stylesheet" type=" text/css">
    <meta charset="UTF-8">
    <title>Staff home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="../src/js/forms.js" defer></script>
    <script src="../src/js/regis_forms.js" defer></script>
    <script src="../src/js/logout.js" defer></script>
    <script src="../src/js/book_prev.js" defer></script>
    <script src="../src/js/search.js" defer></script>
    <script src="../src/js/nav_btns.js" defer></script>
</head>

<body>
    <nav id="top_nav">
        <div id="search_con">
            <input id="book_search" type="text" placeholder="search" name="book_search">
            <div id="search_res">
            </div>
        </div>
        <p class="nav_button"><img src="../src/assets/logo.png"></p>
        <p class="nav_button"><i class="fa-regular fa-calendar"></i></p>
        <p class="nav_button"><i class="fa-regular fa-envelope"></i></p>
        <p class="nav_button menu">
            <i class="fa-solid fa-ellipsis-vertical menu"></i>
        </p>
        <div id="menu_opt_con">
            <p id="about_us">about us</p>
            <p id="logout">logout</p>
            <p id="update_pass">update password</p>
        </div>
    </nav>
   
    <?php require view("side_nav");?>

    <h2>new release</h2>
    <div id="new_release_container" class="card_con book_btn">
        <?php $bview->new_release_books() ?>
    </div>

    <h2>new</h2>
    <div id="new_container" class="card_con book_btn">
        <?php $bview->new_books() ?>
    </div>

    <!-- hidden sections -->

    <?php 
        include view("return_borrow_forms");
        include view("book_preview_change_pass_forms");
        include view("user_book_forms");
    ?>

    
</body>

</html>