<?php
$view = new StaffView;
$bview = new BookView;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../src/style/style.css" rel="stylesheet" type=" text/css">
    <meta charset="UTF-8">
    <title>Page title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="../src/js/regis_forms.js" defer></script>
    <script src="../src/js/change_pass.js" defer></script>
    <script src="../src/js/logout.js" defer></script>
    <script src="../src/js/book_prev.js" defer></script>
    <script src="../src/js/search.js" defer></script>
</head>

<body>
    <nav id="top_nav">
        <div id="search_con">
            <input type="text" placeholder="search">
        </div>
        <p>School logo</p>
        <p class="nav_button"><i class="fa-regular fa-calendar"></i></p>
        <p class="nav_button"><i class="fa-regular fa-envelope"></i></p>
        <p class="nav_button"><i class="fa-solid fa-ellipsis-vertical"></i></p>
    </nav>
    <nav id="side_nav">
        <div><span>Staff</span></div>
        <div id="add_user"><span>User</span><i class="fa-solid fa-circle-plus"></i></div>
        <div id="add_book"><span>Book</span><i class="fa-solid fa-circle-plus"></i></div>
    </nav>

    <h2>new release</h2>
    <div id="new_release_container" class="card_con book_btn">
        <?php $bview->new_release_books() ?>
    </div>

    <h2>new</h2>
    <div id="new_container" class="card_con book_btn">
        <?php $bview->new_books() ?>
    </div>

    <!-- hidden sections -->
    <section id="book_preview" class="regis_form_con">

        <form>
            <section class="card_con">
                <div class="card">
                    <img id="book_prev_img" src="">
                </div>
                <div id="book_main_details">
                    <p id="book_prev_title"> sample title </p>
                    <p id="book_prev_author">(author)</p>
                    <p id="book_prev_date">2020-11-29</p><br>
                    <p id="book_prev_summary">summary</p>

                </div>
                <div id="book_main_button">
                    <button>burrow</button>
                </div>
            </section>
            <hr>
            <div id="book_related">
                <p>Related books...</p><br>
            </div>


            <section id="book_recomendation" class="card_con">
                <div class="card">
                    <img src="https://i.pinimg.com/736x/4f/12/d9/4f12d987e42457b542f023f8131229fc.jpg">
                </div>
                <div class="card">
                    <img src="https://i.pinimg.com/736x/4f/12/d9/4f12d987e42457b542f023f8131229fc.jpg">
                </div>
                <div class="card">
                    <img src="https://i.pinimg.com/736x/4f/12/d9/4f12d987e42457b542f023f8131229fc.jpg">
                </div>
                <div class="card">
                    <img src="https://i.pinimg.com/736x/4f/12/d9/4f12d987e42457b542f023f8131229fc.jpg">
                </div>
            </section>
        </form>
    </section>
     
    <section id="change_pass" class="regis_form_con">
        <form>
            <span><?php echo $view->Username($_SESSION['id']) ?></span><br>
            <input type="text" placeholder="Old password" name="old_pass" required><br>
            <input type="password" placeholder="New password" name="new_pass" required><br>
            <input type="password" placeholder="Confirm password" name="pass" required><br>
            <button type="submit">Update</button>
        </form>
    </section>
    
    <section id="user_regis" class="regis_form_con">
        <form class="regis_form">
            <h1>User Registration</h1>
            <hr>
            <input type="text" name="Studno" placeholder="Student Number" pattern="([0-9]{2})-([0-9]{4,8})" autocomplete="off" required>
            <input type="text" name="fn" placeholder="First Name" pattern="[a-z]*" required><br>
            <input type="text" name="ln" placeholder="Last Name" pattern="[a-z]*" required>
            <input type="text" name="grade/section" placeholder="Grade/Section" pattern="(([a-z]*)/([0-9a-z]*)" required><br>
            <input type="email" name="email" placeholder="Email" required>
            <input type="text" name="contact_no" placeholder="Contact Number" required><br>
            <Button type="submit">Create</Button>
        </form>
    </section>

    <section id="book_regis" class="regis_form_con">
        <form class="regis_form">
            <h1>Add Books</h1>
            <hr>            
            <input type="text" name="title" placeholder="Title">
            <input type="text" name="author" placeholder="Author"><br>
            <input type="text" name="date_release" placeholder="Date release(yyyy-mm-dd)">
            <input type="text" name="genre" placeholder="Genre"><br>
            <label for ="cover_img" >cover image</label>
            <input type="file" name="cover_img"  accept="image/*"><br>
            <input type="text" name="publisher" placeholder="Publisher">
            <input type="text" name="language" placeholder="Language"><br>
            <Button type="submit">Create</Button>
        </form>
    </section>
</body>

</html>