<?php
$view = new StaffView;
$bview = new BookView;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="../src/style/style.css" rel="stylesheet" type=" text/css">
    <meta charset="UTF-8">
    <title>Staff home</title>
    <link rel="stylesheet" href="../src/style/all.min.css">
    <script src="../src/js/forms.js" defer></script>
    <script src="../src/js/regis_forms.js" defer></script>
    <script src="../src/js/logout.js" defer></script>
    <script src="../src/js/book_prev.js" defer></script>
    <script src="../src/js/search.js" defer></script>
    <script src="../src/js/nav_btns.js" defer></script>
</head>

<body>


    <?= get_temp("top_nav"); ?>

    <main>

        <?= get_temp("side_nav", ["view" => $view]); ?>

        <section class="main_con">

            <div>
                <?= $bview->new_release_books(); ?>
            </div>
        </section>
    </main>
    <!--  hidden sections -->
    <?php
    get_temp('loading_pop');
    get_temp("transaction_form");
    get_temp("book_preview_change_pass_forms", ["view" => $view, "bview" => $bview]);
    get_temp("user_book_forms");
    ?>


</body>

</html>