<?php

?>


<!DOCTYPE html>
<html lang="en">

<head>
    <title>User login</title>  
    <link href="../src/style/admin.login.css" rel="stylesheet" type="text/css">
    <link href="../src/style/user.login.css" rel="stylesheet" type="text/css">
    <script src="../src/js/login.js" defer></script>
</head>

<body>

    <img id="logbg" src='../src/assets/bg.png'>

    <form id="form" data-acc_type="user">
        <div class="imgcontainer">
            <img id="logo" src='../src/assets/logo.png'>
        </div>
        <div class="container">

            <input type="text" placeholder="Username" name="user" required><br>
            <input type="password" placeholder="Password" name="pass" required><br>
            <button id="submit" type="submit">Login</button>

        </div>
    </form>

</body>

</html>